### ISSUE TITLE
README에 hello world라도 적어주세요.

### ISSUE THREAD

**Issue by SungminSo** [hgs3896/hgs3896#1]
기껏 레포를 만들었는데 README조차 없는건 조금 그렇잖아요.
사실 이 레포는 README만 있으면 될텐데
이쁘게 꾸미는건 나중에 생각하고 일단 README라도 만들어서 푸시 해주세요.

**Comment by hgs3896** [comment]
Simple is the best인 **컨셉**이라 어쩔수 없습니다.

**Comment by hgs3896** [comment]
@SungminSo [README](https://github.com/hgs3896/hgs3896/blob/main/README.md)를 ~~나름~~ 정성스레 작성해봤습니다.
